# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.6
    hooks:
      - id: ruff-check
      - id: ruff-format
#  - repo: local
#    hooks:
#      - id: ty
#        name: ty type check
#        entry: uv run ty check src/
#        language: system
#        types: [python]
#        pass_filenames: false