# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[complete]
    - name: Lint with ruff
      uses: chartboost/ruff-action@v1
    - name: Test with pytest
      run: |
        pytest --cov-report xml --cov=cchdo
    - name: Test code style with black
      run: |
        black --check .
    - name: Test typing
      run: |
        mypy --namespace-packages --explicit-package-bases cchdo
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
